# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: ruby_thursday
  password: ruby_thursday

development:
  <<: *default
  database: db/ruby_thursday_development

test:
  <<: *default
  database: db/ruby_thursday_test

production:
  <<: *default
  database: db/ruby_thursday_production
